---
- name: Apache server installed
  hosts: web
  become: true
  tasks:
  - name: Apache Stop and Disable
    service:
      name: httpd
      enabled: false
      state: stopped

  - name: Apache Remove
    yum:
      name: httpd
      state: absent
  
  - name: Remove web.html
    command:
      cmd: rm -rf /var/html/web.html
      
