---
- name: Capture Setup
  hosts: node1

  tasks:

    - name: Collect only facts returned by facter
      ansible.builtin.setup:
        filter:
        - '*kernel'
      register: setup

    - debug:
        var: setup